controllers/TaplinkAccountController.php
<?php

namespace app\controllers;

use app\behaviors\NotificationBehavior;
use app\models\taplink\account\TaplinkAccountParams;
use app\models\taplink\account\TaplinkAccountParamsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaplinkAccountController implements the CRUD actions for TaplinkAccountParams model.
 */
class TaplinkAccountController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'notification' =>[
                    'class' => NotificationBehavior::class,
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all TaplinkAccountParams models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new TaplinkAccountParamsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TaplinkAccountParams model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TaplinkAccountParams model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new TaplinkAccountParams();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->validate()) {
                if (!empty($model->serverResponse)) {
                    $model->setAttributes(TaplinkAccountParams::getValidParams($model->serverResponse['response']));
                }
                if ($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
                {
                    $model->loadDefaultValues();
                }
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TaplinkAccountParams model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->validate()) {
            if (!empty($model->serverResponse)) {
                $model->setAttributes(TaplinkAccountParams::getValidParams($model->serverResponse['response']));
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TaplinkAccountParams model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TaplinkAccountParams model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return TaplinkAccountParams the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TaplinkAccountParams::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/TaplinkSubAccountController.php
<?php

namespace app\controllers;

use app\behaviors\NotificationBehavior;
use app\models\taplink\subAccount\TaplinkSubAccountParams;
use app\models\taplink\subAccount\TaplinkSubAccountSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaplinkSubAccountController implements the CRUD actions for TaplinkSubAccountParams model.
 */
class TaplinkSubAccountController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'notification' =>[
                    'class' => NotificationBehavior::class,
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all TaplinkSubAccountParams models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new TaplinkSubAccountSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TaplinkSubAccountParams model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TaplinkSubAccountParams model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new TaplinkSubAccountParams();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TaplinkSubAccountParams model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TaplinkSubAccountParams model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TaplinkSubAccountParams model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return TaplinkSubAccountParams the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TaplinkSubAccountParams::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/taplink-sub-account/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\taplink\subAccount\TaplinkSubAccountParams */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="taplink-sub-account-params-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>
    <?php /*
    <?= $form->field($model, 'taplink_account_params_id')->textInput() ?>

    <?= $form->field($model, 'is_completed')->textInput() ?>

    <?= $form->field($model, 'page_id')->textInput() ?>

    <?= $form->field($model, 'profile_status_id')->textInput() ?>

    <?= $form->field($model, 'tariff_current')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'is_favourite')->textInput() ?>

    <?= $form->field($model, 'is_transfer_pending')->textInput() ?>

    <?= $form->field($model, 'profile_id')->textInput() ?>

    <?= $form->field($model, 'link')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tms_created')->textInput() ?>

    <?= $form->field($model, 'tariff_until')->textInput() ?>

    <?= $form->field($model, 'tariff')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

*/?>
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/taplink-sub-account/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\taplink\subAccount\TaplinkSubAccountSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="taplink-sub-account-params-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'taplink_account_params_id') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'is_completed') ?>

    <?= $form->field($model, 'page_id') ?>

    <?= $form->field($model, 'profile_status_id') ?>

    <?php // echo $form->field($model, 'tariff_current') ?>

    <?php // echo $form->field($model, 'is_favourite') ?>

    <?php // echo $form->field($model, 'is_transfer_pending') ?>

    <?php // echo $form->field($model, 'profile_id') ?>

    <?php // echo $form->field($model, 'link') ?>

    <?php // echo $form->field($model, 'tms_created') ?>

    <?php // echo $form->field($model, 'tariff_until') ?>

    <?php // echo $form->field($model, 'tariff') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'access_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'password') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/taplink-sub-account/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\taplink\subAccount\TaplinkSubAccountParams */

$this->title = Yii::t('app', 'Create Taplink Sub Account Params');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Taplink Sub Account Params'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="taplink-sub-account-params-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/taplink-sub-account/index.php
<?php

use app\models\taplink\account\TaplinkAccountParams;
use app\models\taplink\subAccount\TaplinkSubAccountParams;
use kartik\daterange\DateRangePicker;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\taplink\subAccount\TaplinkSubAccountSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Taplink user profiles');
$this->params['breadcrumbs'][] = $this->title;
$statusList = \app\models\taplink\subAccount\TaplinkSubAccountParams::getStatusList();
$taplinkAccountList = TaplinkAccountParams::getActiveAccountList();
$taplinkLinkList = \app\models\taplink\subAccount\TaplinkSubAccountParams::getParamList('link');
$favouriteList = [0 => 'not favourite', 1 => 'favourite'];
?>
<div class="taplink-sub-account-params-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'taplink_account_params_id',
                'label' => 'Account ',
                'filter' => $taplinkAccountList,
                'format' => 'raw',
                'value' => function ($data) {
                    return Html::a($data->taplinkAccountParams->email, Url::to(['/taplink-account/view', 'id' => $data->taplink_account_params_id]), ['target' => '_blank']);
                }
            ],
            'email',
            [
                'attribute' => 'link',
                'label' => 'Link ',
                'filter' => $taplinkLinkList,
                'format' => 'raw',
            ],
            [
                'attribute' => 'tariff',
                'filter' => \app\models\taplink\subAccount\TaplinkSubAccountParams::getParamList('tariff'),
                'format' => 'raw',
            ],
            [
                'attribute' => 'tariff_current',
                'filter' => \app\models\taplink\subAccount\TaplinkSubAccountParams::getParamList('tariff_current'),
                'format' => 'raw',
            ],
            [
                'attribute' => 'tms_created',
                'format' => ['date', 'php:d.m.Y'],
                'filter' => DateRangePicker::widget(
                    [
                        'model' => $searchModel,
                        'attribute' => 'tms_created',
                        'convertFormat' => true,
                        'pluginOptions' => [
                            'format' => 'php:d.m.Y',
                            'locale' => ['format' => 'Y-m-d'],
                            'todayHighlight' => true
                        ]
                    ]
                ),
                'filterOptions' => [
                    'type' => 'date',
                    'style' => 'min-width:140px',
                ],
            ],
            [
                'attribute' => 'tariff_until',
                'format' => ['date', 'php:d.m.Y'],
                'filter' => DateRangePicker::widget(
                    [
                        'model' => $searchModel,
                        'attribute' => 'tariff_until',
                        'convertFormat' => true,
                        'pluginOptions' => [
                            'format' => 'php:d.m.Y',
                            'locale' => ['format' => 'Y-m-d'],
                            'todayHighlight' => true
                        ]
                    ]
                ),
                'filterOptions' => [
                    'type' => 'date',
                    'style' => 'min-width:140px',
                ],
            ],
            //'is_completed',
            //'page_id',
            'profile_status_id',
            [
                'attribute' => 'is_favourite',
                'format' => 'raw',
                'filter' => $favouriteList,
                'value' => function ($data) use ($favouriteList) {
                    return $favouriteList[$data->is_favourite];
                }
            ],
            //'is_transfer_pending',
            'profile_id',
            [
                'attribute' => 'status',
                'filter' => $statusList,
                'value' => function ($data) use ($statusList) {
                    return ArrayHelper::getValue($statusList, $data->status);
                }
            ],
            [
                'attribute' => 'updated_at',
                'format' => ['date', 'php:d.m.Y'],
                'filter' => DateRangePicker::widget(
                    [
                        'model' => $searchModel,
                        'attribute' => 'updated_at',
                        'convertFormat' => true,
                        'pluginOptions' => [
                            'format' => 'php:d.m.Y',
                            'locale' => ['format' => 'Y-m-d'],
                            'todayHighlight' => true
                        ]
                    ]
                ),
                'filterOptions' => [
                    'type' => 'date',
                    'style' => 'min-width:140px',
                ],
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Actions',
                'headerOptions' => ['style' => 'color:#337ab7'],
                'template' => '{view}{update}{hide}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                            'title' => Yii::t('app', 'account-view'),
                        ]);
                    },

                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                            'title' => Yii::t('app', 'account-update'),
                        ]);
                    },

                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        $url ='/taplink-sub-account/view?id='.$model->id;
                        return $url;
                    }
                    if ($action === 'update') {
                        $url ='/taplink-sub-account/update?id='.$model->id;
                        return $url;
                    }
                }
            ],

            /*
             [
                 'class' => ActionColumn::className(),
                 'urlCreator' => function ($action, TaplinkSubAccountParams $model, $key, $index, $column) {
                     return Url::toRoute([$action, 'id' => $model->id]);
                  }
             ],
            */
        ],
    ]); ?>


</div>

views/taplink-sub-account/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\taplink\subAccount\TaplinkSubAccountParams */

$this->title = Yii::t('app', 'Update Taplink Sub Account Params: {name}', [
    'name' => $model->link,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Taplink Sub Account Params'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="taplink-sub-account-params-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/taplink-sub-account/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\taplink\subAccount\TaplinkSubAccountParams */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Taplink Sub Account Params'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="taplink-sub-account-params-view">

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'taplink_account_params_id',
            'is_completed',
            'page_id',
            'profile_status_id',
            'tariff_current',
            'is_favourite',
            'email',
            'is_transfer_pending',
            'profile_id',
            'link',
            'tms_created',
            'tariff_until',
            'tariff',
            'created_at',
            'updated_at',
            'access_token',
            'email:email',
            'password',
        ],
    ]) ?>

</div>