controllers/TiktokAccountController.php
<?php

namespace app\controllers;

use app\behaviors\NotificationBehavior;
use app\models\tiktok\account\TiktokAccountParams;
use app\models\tiktok\account\TiktokAccountParamsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TiktokAccountController implements the CRUD actions for TiktokAccountParams model.
 */
class TiktokAccountController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'notification' =>[
                    'class' => NotificationBehavior::class,
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all TiktokAccountParams models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new TiktokAccountParamsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TiktokAccountParams model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TiktokAccountParams model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new TiktokAccountParams();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TiktokAccountParams model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->validate()) {
                if (!empty($model->serverResponse)) {

                    /*$model->setAttributes(TiktokAccountParams::getValidParams($model->serverResponse['response']));
                    */
                }
                if ($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
                {
                    $model->loadDefaultValues();
                }
            }
        } else {
            $model->loadDefaultValues();
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TiktokAccountParams model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TiktokAccountParams model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return TiktokAccountParams the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TiktokAccountParams::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/TiktokStrimStatisticController.php
<?php

namespace app\controllers;

use app\behaviors\NotificationBehavior;
use app\models\tiktok\statistic\TiktokStrimStatistic;
use app\models\tiktok\statistic\TiktokStrimStatisticSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TiktokStrimStatisticController implements the CRUD actions for TiktokStrimStatistic model.
 */
class TiktokStrimStatisticController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'notification' =>[
                    'class' => NotificationBehavior::class,
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all TiktokStrimStatistic models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new TiktokStrimStatisticSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TiktokStrimStatistic model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TiktokStrimStatistic model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new TiktokStrimStatistic();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TiktokStrimStatistic model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TiktokStrimStatistic model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TiktokStrimStatistic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return TiktokStrimStatistic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TiktokStrimStatistic::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/tiktok-strim-statistic/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\tiktok\statistic\TiktokStrimStatistic */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tiktok-strim-statistic-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'tiktok_account_params_id')->textInput() ?>

    <?= $form->field($model, 'date')->textInput() ?>

    <?= $form->field($model, 'user_live_views')->textInput() ?>

    <?= $form->field($model, 'user_live_unique_viewers')->textInput() ?>

    <?= $form->field($model, 'user_live_diamonds')->textInput() ?>

    <?= $form->field($model, 'user_live_gift_unique_viewers')->textInput() ?>

    <?= $form->field($model, 'user_live_new_followers')->textInput() ?>

    <?= $form->field($model, 'user_live_duration_time')->textInput() ?>

    <?= $form->field($model, 'user_live_top_viewers')->textInput() ?>

    <?= $form->field($model, 'user_live_follower_diamonds')->textInput() ?>

    <?= $form->field($model, 'user_live_cnt')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tiktok-strim-statistic/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\tiktok\statistic\TiktokStrimStatisticSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tiktok-strim-statistic-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'tiktok_account_params_id') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'user_live_views') ?>

    <?= $form->field($model, 'user_live_unique_viewers') ?>

    <?php // echo $form->field($model, 'user_live_diamonds') ?>

    <?php // echo $form->field($model, 'user_live_gift_unique_viewers') ?>

    <?php // echo $form->field($model, 'user_live_new_followers') ?>

    <?php // echo $form->field($model, 'user_live_duration_time') ?>

    <?php // echo $form->field($model, 'user_live_top_viewers') ?>

    <?php // echo $form->field($model, 'user_live_follower_diamonds') ?>

    <?php // echo $form->field($model, 'user_live_cnt') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tiktok-strim-statistic/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\tiktok\statistic\TiktokStrimStatistic */

$this->title = Yii::t('app', 'Create Tiktok Strim Statistic');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tiktok Strim Statistics'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tiktok-strim-statistic-create">
<?php /*
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
*/?>
</div>

views/tiktok-strim-statistic/index.php
<?php

use app\widgets\PageSizeWidget;
use kartik\daterange\DateRangePicker;
use kartik\export\ExportMenu;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\tiktok\statistic\TiktokStrimStatisticSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Tiktok Strim Statistics');
$this->params['breadcrumbs'][] = $this->title;
$tiktokAccountList = \app\models\tiktok\account\TiktokAccountParams::getActiveAccountList();
?>
<div class="tiktok-strim-statistic-index">

    <?= PageSizeWidget::widget()?>
    <?php
    $columns =[
        [
            'attribute' => 'tiktok_account_params_id',
            'label' => 'Profile ',
            'filter' => $tiktokAccountList,
            'format' => 'raw',
            'value' => function ($data) {
                return Html::a($data->tiktokAccountParams->username, Url::to(['/tiktok-account/view', 'id' => $data->tiktok_account_params_id]), ['target' => '_blank']);
            }
        ],
        [
            'attribute' => 'date',
            'format' => ['date', 'php:d.m.Y'],
            'filter' => DateRangePicker::widget(
                [
                    'model' => $searchModel,
                    'attribute' => 'date',
                    'convertFormat' => true,
                    'pluginOptions' => [
                        'format' => 'php:d.m.Y',
                        'locale' => ['format' => 'Y-m-d'],
                        'todayHighlight' => true
                    ]
                ]
            ),
            'filterOptions' => [
                'type' => 'date',
                'style' => 'min-width:140px',
            ],
        ],
        'live_views',
        'live_unique_viewers',
        'live_diamonds',
        'live_gift_unique_viewers',
        'live_new_followers',
        'live_duration_time',
        'live_top_viewers',
        'live_follower_diamonds',
        'live_cnt',
        [
            'attribute' => 'updated_at',
            'format' => ['date', 'php:d.m.Y'],
            'filter'=>DateRangePicker::widget(
                [
                    'model' => $searchModel,
                    'attribute' => 'updated_at',
                    'convertFormat' => true,
                    'pluginOptions' => [
                        'format' => 'php:d.m.Y',
                        'locale' => ['format' => 'Y-m-d'],
                        'todayHighlight' => true
                    ]
                ]
            ),
            'filterOptions' => [
                'type' => 'date',
                'style' => 'min-width:140px',
            ],
        ],
        //'created_at',
        /*[
            'class' => ActionColumn::className(),
            'urlCreator' => function ($action, TiktokStrimStatistic $model, $key, $index, $column) {
                return Url::toRoute([$action, 'id' => $model->id]);
            }
        ],*/
    ];
    ?>
    <?= ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'clearBuffers' => true,
        'exportConfig' => [
            ExportMenu::FORMAT_EXCEL => false,
            ExportMenu::FORMAT_TEXT => false,
            ExportMenu::FORMAT_HTML => false,
        ],
        'filename' => 'tiktok_strim_stats_data('.date('d-M-Y').')'
    ]);
    ?>


    <?= \kartik\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columns,
    ]); ?>

</div>

views/tiktok-strim-statistic/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\tiktok\statistic\TiktokStrimStatistic */

$this->title = Yii::t('app', 'Update Tiktok Strim Statistic: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tiktok Strim Statistics'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="tiktok-strim-statistic-update">
<?php /*
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    */?>
</div>

views/tiktok-strim-statistic/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\tiktok\statistic\TiktokStrimStatistic */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tiktok Strim Statistics'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="tiktok-strim-statistic-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'tiktok_account_params_id',
            'date',
            'user_live_views',
            'user_live_unique_viewers',
            'user_live_diamonds',
            'user_live_gift_unique_viewers',
            'user_live_new_followers',
            'user_live_duration_time:datetime',
            'user_live_top_viewers',
            'user_live_follower_diamonds',
            'user_live_cnt',
            'updated_at',
            'created_at',
        ],
    ]) ?>

</div>