controllers/BinpartnerAccountController.php
<?php

namespace app\controllers;

use app\behaviors\NotificationBehavior;
use app\models\binpartner\account\BinpartnerAccountParams;
use app\models\binpartner\account\BinpartnerAccountParamsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BinpartnerAccountParamsController implements the CRUD actions for BinpartnerAccountParams model.
 */
class BinpartnerAccountController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'notification' => [
                    'class' => NotificationBehavior::class,
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all BinpartnerAccountParams models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new BinpartnerAccountParamsSearch();
        $searchModel->status = BinpartnerAccountParams::STATUS_ENABLE;
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BinpartnerAccountParams model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new BinpartnerAccountParams model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new BinpartnerAccountParams();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing BinpartnerAccountParams model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing BinpartnerAccountParams model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionSetDisableStatus($id)
    {
        $this->findModel($id)->updateAttributes(['status' => BinpartnerAccountParams::STATUS_DISABLE]);
        return $this->redirect(['index']);
    }

    /**
     * Finds the BinpartnerAccountParams model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return BinpartnerAccountParams the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BinpartnerAccountParams::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/BinpartnerStatisticController.php
<?php

namespace app\controllers;

use app\behaviors\NotificationBehavior;
use app\models\binpartner\statistic\BinpartnerStatistic;
use app\models\binpartner\statistic\BinpartnerStatisticSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BinpartnerStatisticController implements the CRUD actions for BinpartnerStatistic model.
 */
class BinpartnerStatisticController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'notification' =>[
                    'class' => NotificationBehavior::class,
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all BinpartnerStatistic models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new BinpartnerStatisticSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BinpartnerStatistic model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new BinpartnerStatistic model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new BinpartnerStatistic();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing BinpartnerStatistic model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    /*
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    */

    /**
     * Deletes an existing BinpartnerStatistic model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    /*public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }*/

    /**
     * Finds the BinpartnerStatistic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return BinpartnerStatistic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BinpartnerStatistic::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/binpartner-statistic/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model models\binpartner\statistic\BinpartnerStatistic */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="binpartner-statistic-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'binpartner_account_params_id')->textInput() ?>

    <?= $form->field($model, 'day')->textInput() ?>

    <?= $form->field($model, 'visitors')->textInput() ?>

    <?= $form->field($model, 'reg')->textInput() ?>

    <?= $form->field($model, 'conf')->textInput() ?>

    <?= $form->field($model, 'ctr')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'demo')->textInput() ?>

    <?= $form->field($model, 'ftd')->textInput() ?>

    <?= $form->field($model, 'ftds')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'first_ratio')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'sign_up_ratio')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deposits_count')->textInput() ?>

    <?= $form->field($model, 'deposits')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'traders')->textInput() ?>

    <?= $form->field($model, 'deals_count')->textInput() ?>

    <?= $form->field($model, 'deals')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'flows')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'withs')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'profit')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/binpartner-statistic/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model models\binpartner\statistic\BinpartnerStatisticSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="binpartner-statistic-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'binpartner_account_params_id') ?>

    <?= $form->field($model, 'day') ?>

    <?= $form->field($model, 'visitors') ?>

    <?= $form->field($model, 'reg') ?>

    <?php // echo $form->field($model, 'conf') ?>

    <?php // echo $form->field($model, 'ctr') ?>

    <?php // echo $form->field($model, 'demo') ?>

    <?php // echo $form->field($model, 'ftd') ?>

    <?php // echo $form->field($model, 'ftds') ?>

    <?php // echo $form->field($model, 'first_ratio') ?>

    <?php // echo $form->field($model, 'sign_up_ratio') ?>

    <?php // echo $form->field($model, 'deposits_count') ?>

    <?php // echo $form->field($model, 'deposits') ?>

    <?php // echo $form->field($model, 'traders') ?>

    <?php // echo $form->field($model, 'deals_count') ?>

    <?php // echo $form->field($model, 'deals') ?>

    <?php // echo $form->field($model, 'flows') ?>

    <?php // echo $form->field($model, 'withs') ?>

    <?php // echo $form->field($model, 'profit') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/binpartner-statistic/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model models\binpartner\statistic\BinpartnerStatistic */

$this->title = Yii::t('app', 'Create Binpartner Statistic');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Binpartner Statistics'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="binpartner-statistic-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/binpartner-statistic/index.php
<?php

use app\models\binpartner\statistic\BinpartnerStatistic;
use app\widgets\PageSizeWidget;
use kartik\daterange\DateRangePicker;
use \yii\helpers\Html;
use \yii\helpers\Url;
use yii\grid\GridView;
use kartik\export\ExportMenu;
use \app\models\binpartner\account\BinpartnerAccountParams;

/* @var $this yii\web\View */
/* @var $searchModel app\models\binpartner\statistic\BinpartnerStatisticSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Binpartner Statistics');
$this->params['breadcrumbs'][] = $this->title;
$binpartnerAccountList = BinpartnerAccountParams::getActiveAccountList();
?>
<div class="binpartner-statistic-index">
    <?= PageSizeWidget::widget()?>
    <?php // echo $this->render('_search', ['model' => $searchModel]);


    $columns = [
        [
            'attribute' => 'binpartner_account_params_id',
            'label' => 'Email ',
            'filter' => $binpartnerAccountList,
            'format' => 'raw',
            'value' => function ($data) {
                return Html::a($data->binpartnerAccountParams->email, Url::to(['/binpartner-account/view', 'id' => $data->binpartner_account_params_id]), ['target' => '_blank']);
            }
        ],
        [
            'attribute' => 'day',
            'format' => ['date', 'php:d.m.Y'],
            'filter' => DateRangePicker::widget(
                [
                    'model' => $searchModel,
                    'attribute' => 'day',
                    'convertFormat' => true,
                    'pluginOptions' => [
                        'format' => 'php:d.m.Y',
                        'locale' => ['format' => 'Y-m-d'],
                        'todayHighlight' => true
                    ]
                ]
            ),
            'filterOptions' => [
                'type' => 'date',
                'style' => 'min-width:140px',
            ],
        ],
        'visitors',
        'reg',
        'conf',
        [
            'attribute' => 'ctr',
            'value' => function ($data) {
                return $data->ctr . '%';
            }
        ],
        'demo',
        'ftd',
        [
            'attribute' => 'ftds',
            'value' => function ($data) {
                return $data->ftds . '$';
            }
        ],
        [
            'attribute' => 'ratio',
            'value' => function ($data) {
                return $data->first_ratio . '%/' . $data->sign_up_ratio . '%';
            }
        ],
        'deposits_count',
        [
            'attribute' => 'deposits',
            'value' => function ($data) {
                return $data->deposits . '$';
            }
        ],
        'traders',
        'deals_count',
        [
            'attribute' => 'deals',
            'value' => function ($data) {
                return $data->deals . '$';
            }
        ],
        [
            'attribute' => 'flows',
            'value' => function ($data) {
                return $data->flows . '$';
            }
        ],
        [
            'attribute' => 'withs',
            'value' => function ($data) {
                return $data->withs . '$';
            }
        ],
        [
            'attribute' => 'profit',
            'value' => function ($data) {
                return $data->profit . '$';
            }
        ],
        /*[
            'class' => ActionColumn::className(),
            'urlCreator' => function ($action, BinpartnerStatistic $model, $key, $index, $column) {
                return Url::toRoute([$action, 'id' => $model->id]);
             }
        ],*/
    ];
    ?>

    <?= ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'clearBuffers' => true,
        'exportConfig' => [
                ExportMenu::FORMAT_EXCEL => false,
                ExportMenu::FORMAT_TEXT => false,
                ExportMenu::FORMAT_HTML => false,
        ],
        'filename' => 'binpartner_common_stats_data('.date('d-M-Y').')'
    ]);
    ?>

    <?= \kartik\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columns,
    ]); ?>


</div>

views/binpartner-statistic/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\binpartner\statistic\BinpartnerStatistic */

$this->title = Yii::t('app', 'Update Binpartner Statistic: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Binpartner Statistics'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="binpartner-statistic-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/binpartner-statistic/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model models\binpartner\statistic\BinpartnerStatistic */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Binpartner Statistics'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="binpartner-statistic-view">


    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'binpartner_account_params_id',
            'day',
            'visitors',
            'reg',
            'conf',
            'ctr',
            'demo',
            'ftd',
            'ftds',
            'first_ratio',
            'sign_up_ratio',
            'deposits_count',
            'deposits',
            'traders',
            'deals_count',
            'deals',
            'flows',
            'withs',
            'profit',
        ],
    ]) ?>

</div>